import Head from "next/head";
import Header from "../../components/home/Header";
import HeroSection from "../../components/home/HeroSection";
import SearchSection from "../../components/home/SearchSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <HeroSection />
        <SearchSection />
      </main>
    </>
  );
}
